"""
ME 144/244: Modeling, Simulation, and Digital Twins of Drone-Based Systems 
Project 2: Swarm
Spring 2026 Semester
GSI - Tommy Hosmer
"""
import pickle
"""
This script writes the parameters to a dictionary in a pickle file that can be read in during the simulation. 
Separating from full sim makes things cleaner.
"""

# System Parameters
Nm = 15                                        # number of initial agents
No = 25                                        # number of obstacles
Nt = 100                                        # number of targets to map

# Physical Parameters
Ai  = 1                           # agent characteristic area (m^2)
Cdi = .25                           # agent coefficient of drag
mi  = 10                           # agent mass (kg)
va  = 0                           # Air velocity (m/s)
ra  = 1.225                           # Air Density (kg/m^3)
Fp  = 200                           # Propulsion force magnitude (N)

# Time Stepping Parameters
dt = 0.2                                        # time step size (s)
tf = 60                                        # Maximum task time (s)

# Object Interaction Parameters
agent_sight = 5                                 # maximum target mapping distance
crash_range = 2                                 # agent collision distance

# Genetic Algorithm Parameters
K = 6                                          # Strings generated by breeding (Children)
P = 6                                          # Surviving strings for breeding (Parents)
S = 20                                          # Design strings per generation
G = 100                                          # Total Generations
minLam = 0                                     # Minimum value of design strings
maxLam = 2                                     # Maximum value of design strings
numLam = 15

w1 = 70                                         # Weight of mapping in net cost
w2 = 10                                         # Weight of time usage in net cost
w3 = 20                                         # Weight of agent losses in net cost

# Domain Parameters
xmax = 150                                      # x bound of domain
ymax = 150                                      # y bound of domain
zmax = 60                                      # z bound of domain

locx = 100                                      # x bound of target/obstacle region
locy = 100                                      # y bound of target/obstacle region
locz = 10
tolerance = 0.01

# Store the parameters in a dictionary
parameters_dict = {
    "Nm": Nm,
    "No": No,
    "Nt": Nt,
    "Ai": Ai,
    "Cdi": Cdi,
    "mi": mi,
    "va": va,
    "ra": ra,
    "Fp": Fp,
    "dt": dt,
    "tf": tf,
    "agent_sight": agent_sight,
    "crash_range": crash_range,
    "K": K,
    "P": P,
    "S": S,
    "G": G,
    "minLam": minLam,
    "maxLam": maxLam,
    "numLam": numLam,
    "w1": w1,
    "w2": w2,
    "w3": w3,
    "xmax": xmax,
    "ymax": ymax,
    "zmax": zmax,
    "locx": locx,
    "locy": locy,
    "locz": locz,
    "tolerance": tolerance
}

# Write the dictionary to a pickle file

with open('parameters.pkl', 'wb') as pkl_file:
    pickle.dump(parameters_dict, pkl_file)
